[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"
